name: My-Actions

on:
  push:
    branches:
      - main

jobs:
  Windows-test:
    runs-on: windows-latest
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
      - name: List current folder
        run: dir
#      - name: Print system info of Win machine
#        run: |
#          echo "Hi! There is info about me"
#          cd C:\Windows\System32
#          systeminfo

  Windows-AS-test:
      runs-on: windows-latest
      needs: [Windows-test]
      steps:
        - name: Check gcc
          run: gcc --version
        
        

  Linux-test:
    runs-on: ubuntu-latest
    needs: [Windows-test]
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
      - name: List current folder
        run: ls -la
#      - name: Print system info of Linux(ubuntu) machine
#        run: |
#          echo "Hi! There is info about me"
#          hostnamectl
        
  Linux-AS-test:
      runs-on: ubuntu-latest
      needs: [Linux-test] 
      steps:
        - name: Check gcc
          run: gcc --version
        

